name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  no-options:
    name: Test ai-digest action without options
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: codebase.md
      DIGEST_LOG: ingest.md

    steps:
      - uses: actions/checkout@v4
        with:
          path: ai-digest
          clean: true

      - name: Run action
        id: run_action
        uses: ./ai-digest

      - name: Check output files exist
        run: |
          test -f ${{ env.OUTPUT_FILE }}
          test -f ${{ env.DIGEST_LOG }}

      - name: Check outputs
        run: |
          test ${{ steps.run_action.outputs.included_files }} -gt 0
          test ${{ steps.run_action.outputs.estimated_tokens }} -gt 0
          test ${{ steps.run_action.outputs.binary_files }} -eq 0
          test ${{ steps.run_action.outputs.total_files }} -gt 0

          # Verify files are listed in the digest
          cat ${{ env.DIGEST_LOG }} | grep 'README.md'

  all-options:
    name: Test ai-digest action specifying all options
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: workflows.md
      DIGEST_LOG: workflows-ingest.md

    steps:
      - uses: actions/checkout@v4
        with:
          path: ai-digest
          clean: true

      - name: Run action
        id: run_action
        uses: ./ai-digest
        with:
          input_path: './ai-digest/.github/workflows'
          output_file: ${{ env.OUTPUT_FILE }}
          digest_log: ${{ env.DIGEST_LOG }}
          ai_digest_flags: '--whitespace-removal --show-output-files'

      - name: Check output files exist
        run: |
          test -f ${{ env.OUTPUT_FILE }}
          test -f ${{ env.DIGEST_LOG }}

      - name: Check outputs
        run: |
          test ${{ steps.run_action.outputs.included_files }} -gt 0
          test ${{ steps.run_action.outputs.estimated_tokens }} -gt 0
          test ${{ steps.run_action.outputs.binary_files }} -eq 0
          test ${{ steps.run_action.outputs.total_files }} -gt 0

          # Verify files are listed in the digest
          cat ${{ env.DIGEST_LOG }} | grep 'test.yml'

  no-output-file-listing:
    name: Test ai-digest action can exclude file listing in digest log
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: no-file-listing.md
      DIGEST_LOG: no-file-listing-ingest.md

    steps:
      - uses: actions/checkout@v4
        with:
          path: ai-digest
          clean: true

      - name: Run action
        id: run_action
        uses: ./ai-digest
        with:
          input_path: './ai-digest/.github/workflows'
          output_file: ${{ env.OUTPUT_FILE }}
          digest_log: ${{ env.DIGEST_LOG }}
          ai_digest_flags: '--whitespace-removal'

      - name: Check no file listing is included in the digest log
        run: |
          test ${{ steps.run_action.outputs.included_files }} -gt 0
          test ${{ steps.run_action.outputs.total_files }} -gt 0

          # Verify files are not listed in the digest
          test -f ${{ env.DIGEST_LOG }}
          test -z "$(cat ${{ env.DIGEST_LOG }} | grep 'test.yml')"
